#Requires -Version 5.1
<#
.SYNOPSIS
    Install Claude Dispatcher globally — one-time setup.
.DESCRIPTION
    Generates ~/.claude/settings.json with absolute paths to hooks.
    Run this once after cloning the repo into ~/.claude/:

        git clone <repo-url> $env:USERPROFILE\.claude
        pwsh $env:USERPROFILE\.claude\Install.ps1

    After that, the dispatcher is active in every project automatically.
.PARAMETER ClaudeDir
    Path to your Claude profile directory. Default: $env:USERPROFILE\.claude
    (or $HOME/.claude on Linux/macOS)
.PARAMETER Force
    Overwrite existing settings.json without prompting.
.PARAMETER AddToPath
    Add <ClaudeDir>\scripts to the current user's PATH permanently.
#>
param(
    [string] $ClaudeDir = "",
    [switch] $Force,
    [switch] $AddToPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve install directory ──────────────────────────────────
if (-not $ClaudeDir) {
    if ($env:USERPROFILE) {
        $ClaudeDir = Join-Path $env:USERPROFILE ".claude"
    } else {
        $ClaudeDir = Join-Path $HOME ".claude"
    }
}
$ClaudeDir = [System.IO.Path]::GetFullPath($ClaudeDir)

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║   CLAUDE DISPATCHER — GLOBAL INSTALL                      ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Install directory : $ClaudeDir" -ForegroundColor White
Write-Host ""

# ── Verify this script lives inside ClaudeDir ─────────────────
$scriptClaudeDir = [System.IO.Path]::GetFullPath($PSScriptRoot)
if ($scriptClaudeDir -ne $ClaudeDir) {
    Write-Host "[WARN] This script is at: $PSScriptRoot" -ForegroundColor Yellow
    Write-Host "       Expected location: $ClaudeDir" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  Typical install steps:" -ForegroundColor DarkGray
    Write-Host "    git clone <repo> `"$ClaudeDir`"" -ForegroundColor DarkGray
    Write-Host "    pwsh `"$ClaudeDir\Install.ps1`"" -ForegroundColor DarkGray
    Write-Host ""
    $answer = Read-Host "Continue anyway? (y/N)"
    if ($answer -notmatch '^[Yy]') { exit 1 }
}

# ── Paths ──────────────────────────────────────────────────────
$hooksDir    = Join-Path $ClaudeDir "hooks"
$scriptsDir  = Join-Path $ClaudeDir "scripts"
$onPrompt    = Join-Path $hooksDir "on-prompt.ps1"
$preBash     = Join-Path $hooksDir "pre-bash.ps1"
$settingsOut = Join-Path $ClaudeDir "settings.json"
$template    = Join-Path $ClaudeDir "settings.json.template"

# ── Validate required files exist ─────────────────────────────
$required = @($onPrompt, $preBash, (Join-Path $scriptsDir "Invoke-Chain.ps1"))
$missing  = $required | Where-Object { -not (Test-Path $_) }
if ($missing) {
    Write-Host "[ERROR] Missing files (repo may be incomplete):" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    exit 1
}

# ── Check if settings.json already exists ─────────────────────
if ((Test-Path $settingsOut) -and -not $Force) {
    Write-Host "[INFO] $settingsOut already exists." -ForegroundColor Yellow
    $answer = Read-Host "Overwrite? (y/N)"
    if ($answer -notmatch '^[Yy]') {
        Write-Host "Skipped. Use -Force to overwrite without prompting." -ForegroundColor DarkGray
        Write-Host ""
        goto_done
    }
}

# ── Escape backslashes for JSON ───────────────────────────────
$onPromptJson = $onPrompt -replace '\\', '\\'
$preBashJson  = $preBash  -replace '\\', '\\'

# ── Generate settings.json ────────────────────────────────────
$settingsContent = @"
{
  "_comment": "Auto-generated by Install.ps1 — do not edit manually. Re-run Install.ps1 to regenerate.",
  "skills": {
    "directory": "$($ClaudeDir -replace '\\','\\')\\skills"
  },
  "env": {
    "DISPATCHER_PROFILE_DIR": "$($ClaudeDir -replace '\\','\\\\')"
  },
  "hooks": {
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "pwsh -NoProfile -NonInteractive -File \"$onPromptJson\""
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "pwsh -NoProfile -NonInteractive -File \"$preBashJson\""
          }
        ]
      }
    ]
  },
  "permissions": {
    "allow": [
      "Bash(pwsh*)",
      "Bash(powershell*)",
      "Bash(gemini*)",
      "Bash(codex*)",
      "Bash(mods*)"
    ]
  }
}
"@

$settingsContent | Out-File $settingsOut -Encoding UTF8 -Force
Write-Host "[OK] Generated: $settingsOut" -ForegroundColor Green

# ── Optionally add scripts to PATH ────────────────────────────
if ($AddToPath) {
    $currentPath = [System.Environment]::GetEnvironmentVariable("PATH", "User")
    if ($currentPath -notlike "*$scriptsDir*") {
        [System.Environment]::SetEnvironmentVariable(
            "PATH",
            "$currentPath;$scriptsDir",
            "User"
        )
        Write-Host "[OK] Added to PATH (User): $scriptsDir" -ForegroundColor Green
        Write-Host "     Restart your terminal for PATH changes to take effect." -ForegroundColor DarkGray
    } else {
        Write-Host "[OK] Already in PATH: $scriptsDir" -ForegroundColor DarkGray
    }
}

# ── Summary ───────────────────────────────────────────────────
Write-Host ""
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  How it works:" -ForegroundColor Cyan
Write-Host "    - Hooks in settings.json point to: $hooksDir" -ForegroundColor White
Write-Host "    - Config priority: <project>\.claude\dispatcher.config.json  ->  $ClaudeDir\dispatcher.config.json" -ForegroundColor White
Write-Host "    - CLAUDE.md in $ClaudeDir applies globally to all projects" -ForegroundColor White
Write-Host ""
Write-Host "  To override chain for a specific project:" -ForegroundColor Cyan
Write-Host "    Create .claude\dispatcher.config.json in your project root" -ForegroundColor White
Write-Host ""
Write-Host "  To run with dispatcher from any project:" -ForegroundColor Cyan
Write-Host "    claude   (hooks activate automatically)" -ForegroundColor White
if ($AddToPath) {
    Write-Host "    Invoke-Chain -Task `"your task`"  (after terminal restart)" -ForegroundColor White
} else {
    Write-Host "    pwsh `"$scriptsDir\Invoke-Chain.ps1`" -Task `"your task`"" -ForegroundColor White
    Write-Host "    (run with -AddToPath to add scripts to PATH for shorter syntax)" -ForegroundColor DarkGray
}
Write-Host ""
