#Requires -Version 5.1
<#
.SYNOPSIS
    Claude sub-agent — runs 'claude -p' for an intermediate chain step.
.DESCRIPTION
    Spawns a non-interactive Claude Code instance to perform a specific role
    (e.g., global-planner, implementation-planner) within the chain.
    The sub-agent gets the role system prompt + accumulated context as input,
    and returns structured output for the next step.
.PARAMETER Role
    Role name matching a file in .claude/roles/<role>.md
.PARAMETER Task
    Original user task.
.PARAMETER Context
    Accumulated output from previous chain steps.
.PARAMETER OutputFile
    Where to save this step's output.
.PARAMETER RolesDir
    Path to the roles directory. Default: .claude\roles
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string]$Role,
    [Parameter(Mandatory)] [string]$Task,
    [Parameter()]          [string]$Context = "",
    [Parameter(Mandatory)] [string]$OutputFile,
    [Parameter()]          [string]$RolesDir = ".claude\roles"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Load role definition ───────────────────────────────────────
$rolePath = Join-Path $RolesDir "$Role.md"
if (-not (Test-Path $rolePath)) {
    throw "Role definition not found: $rolePath"
}
$roleDefinition = Get-Content $rolePath -Raw -Encoding UTF8

# ── Build prompt for sub-agent ────────────────────────────────
$prompt = @"
$roleDefinition

---
## ORIGINAL USER TASK
$Task

"@

if ($Context.Trim()) {
    $prompt += @"

## ACCUMULATED CONTEXT FROM PREVIOUS STEPS
$Context
"@
}

$prompt += @"

---
Now perform your role as defined above. Output ONLY the structured format specified.
"@

# Save prompt for inspection
$promptFile = [System.IO.Path]::ChangeExtension($OutputFile, '.prompt.txt')
$prompt | Out-File -FilePath $promptFile -Encoding UTF8

# ── Check if claude CLI is available ──────────────────────────
$claudeCmd = Get-Command 'claude' -ErrorAction SilentlyContinue
if (-not $claudeCmd) {
    Write-Host "  [WARN] 'claude' not in PATH — using fallback inline response" -ForegroundColor Yellow
    # Fallback: generate a minimal structured plan inline
    $fallback = @"
GLOBAL_PLAN_START
task_summary: $Task
complexity: medium
domain: general
language: auto
research_needed: yes
research_objective: What are the best practices and patterns for: $Task
implementation_objective: Implement a working solution for: $Task
review_focus: correctness and security
notes: Generated by fallback (claude CLI not available)
GLOBAL_PLAN_END
"@
    $fallback | Out-File -FilePath $OutputFile -Encoding UTF8
    return @{ Success = $true; OutputFile = $OutputFile; Agent = 'claude-fallback'; Role = $Role }
}

# ── Run claude -p (non-interactive print mode) ─────────────────
Write-Host "  [claude:$Role] Running sub-agent..." -ForegroundColor Cyan

$output = ""
$success = $false

try {
    # Primary: pipe prompt via stdin to claude -p
    # --dangerously-skip-permissions = YOLO mode: no tool-use confirmations
    # This is needed for sub-agent to run autonomously without blocking on prompts.
    $output = $prompt | & claude -p --dangerously-skip-permissions 2>&1
    if ($LASTEXITCODE -eq 0 -or $output) {
        $success = $true
    }
} catch {
    Write-Host "  [WARN] claude -p stdin failed: $_" -ForegroundColor Yellow
}

if (-not $success) {
    try {
        # Fallback: save prompt to temp file, pass as argument
        $tmpPrompt = Join-Path $env:TEMP "claude-agent-prompt-$(Get-Date -Format 'HHmmss').txt"
        $prompt | Out-File $tmpPrompt -Encoding UTF8
        $output = & claude -p --dangerously-skip-permissions (Get-Content $tmpPrompt -Raw) 2>&1
        Remove-Item $tmpPrompt -ErrorAction SilentlyContinue
        if ($output) { $success = $true }
    } catch {
        Write-Host "  [WARN] claude -p fallback also failed: $_" -ForegroundColor Yellow
    }
}

if (-not $success -or -not $output) {
    throw "Claude sub-agent failed for role '$Role'. Ensure 'claude' is in PATH and ANTHROPIC_API_KEY is set."
}

# ── Save output ────────────────────────────────────────────────
$output | Out-File -FilePath $OutputFile -Encoding UTF8
Write-Host "  [claude:$Role] Done → $OutputFile" -ForegroundColor Green

return @{
    Success    = $true
    OutputFile = $OutputFile
    Agent      = 'claude'
    Role       = $Role
    Output     = $output
}
